# ci.yml file for GitHub Actions
name: CI

on: [push, pull_request]

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Lint"
            cmd: "npm run lint:check"
          - name: "Typecheck"
            cmd: "npm run typecheck"
          - name: "Test"
            cmd: "./node_modules/cypress/bin/cypress install && npm run test && cp coverage/coverage-summary.json coverage-summary.json && mv coverage/lcov-report lcov-report"
          - name: "Test Isolated"
            cmd: "./node_modules/cypress/bin/cypress install && npm run test:isolated"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v3
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: ${{ matrix.name }}
        run: ${{ matrix.cmd }}

      - name: get coverage badge
        if: ${{ matrix.name == 'Test' }}
        run: |
          curl $(
            cat coverage/coverage-summary.json \
            | python3 -c  "import sys, json; pct = round(json.load(sys.stdin)['total']['lines']['pct']); color = 'success' if pct > 80 else 'yellow' if pct > 60 else 'critical'; print(f'https://img.shields.io/badge/test%20coverage-{pct}-{color}')"
          ) > test-coverage.svg

      - name: upload coverage
        if: ${{ matrix.name == 'Test' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: |
            test-coverage.svg
            lcov-report
          retention-days: 1

  build_docs:
    runs-on: ubuntu-latest
    needs: ["ci_checks"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v3
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create the docs directory locally in CI
        run: npm run docs

      # TODO: bound to be an easier way to get
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: test-coverage

      - name: mv badge
        run: mv test-coverage.svg lcov-report docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
