# ci.yml file for GitHub Actions
name: CI

on: [push, pull_request]

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Lint"
            cmd: "npm run lint:check"
          - name: "Typecheck"
            cmd: "npm run typecheck"
          - name: "Test"
            cmd: "./node_modules/cypress/bin/cypress install && npm run test"
          - name: "Test Isolated"
            cmd: "./node_modules/cypress/bin/cypress install && npm run test:isolated"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v3
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: ${{ matrix.name }}
        run: ${{ matrix.cmd }}

  build_docs:
    runs-on: ubuntu-latest
    # TODO: commenting for now so that docs build immediately for faster feedback loop
    # needs: ["ci_checks"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v3
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create the docs directory locally in CI
        run: npm run docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
